version: '3.7'
services:
  app:
    build: ./
    container_name: app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - '9000:9000'
    networks:
      - app-php
    extra_hosts:
      - host.docker.internal:host-gateway
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php
networks:
  app-php:
    driver: bridge
